In [44]:
import numpy as np
a = np.array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
a
out = np.ones(a.size);
out = out.reshape(a.size, 1)
out.shape
#np.c_[out]
#out.shape#.shape[1]

(12, 1)

In [15]:
u = np.linspace(-1, 1.5, 50);
v = np.linspace(-1, 1.5, 50);
z = np.zeros((len(u), len(v)));

#z = z.T;


0
1
2
3
4


In [81]:
y = a[:,1]
y

array([ 2,  5,  8, 11])

In [82]:
m = len(y);
m

4

In [83]:
np.ones(m, int)


array([1, 1, 1, 1])

In [84]:
np.zeros(2, int)


array([0, 0])

In [85]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [86]:
[np.ones(m, int), a[:,1]]

[array([1, 1, 1, 1]), array([ 2,  5,  8, 11])]

In [87]:
print(a)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [88]:
b= np.array([1, 2, 3])



In [89]:
b

array([1, 2, 3])

In [90]:
print(np.transpose(b))

[1 2 3]


In [91]:
np.size(a)

12

In [92]:
a.shape


(4, 3)

In [93]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [94]:
b

array([1, 2, 3])

In [95]:
b.shape

(3,)

In [96]:
c = np.transpose(b)
c.shape

(3,)

In [97]:
c

array([1, 2, 3])

In [98]:
a = np.array([1, 2])
a


array([1, 2])

In [99]:
b = np.array([[5, 6], [7, 8]])
np.matmul(a, b)

array([19, 22])

In [100]:
a = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],[7, 8, 34,4,4,4,5,4,3,2]])
b = np.zeros((2,1))
np.dot(a.T, b)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [101]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [102]:
np.array([-1, 2])


array([-1,  2])

In [103]:
np.array([-1, 2]).T

array([-1,  2])

In [104]:
np.transpose(np.array([-1, 2]))


array([-1,  2])

In [105]:
np.array([[-1, 2], []]).shape


(2,)

In [106]:
np.array([-1, 2]).T

array([-1,  2])

In [107]:
b = np.zeros((2,1))

In [108]:
b

array([[0.],
       [0.]])

In [109]:
theta = np.zeros((2, 1), int);

In [110]:

theta[1]

array([0])

In [111]:
import numpy as np
x = list(range(1, 5))
y = list(range(1, 10))
print(x)
print("----------------")
print(y)
print("----------------")
X, Y = np.meshgrid(y, x)
print(X)
print("----------------")
print(Y)
print("----------------")

[1, 2, 3, 4]
----------------
[1, 2, 3, 4, 5, 6, 7, 8, 9]
----------------
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
----------------
[[1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4]]
----------------


In [112]:
np.c_[np.array([[1, 2, 3]]),0, 0, np.array([[4,5,6]])]

array([[1, 2, 3, 0, 0, 4, 5, 6]])

In [113]:
np.array([[1,2,3], [1, 2, 3]])

array([[1, 2, 3],
       [1, 2, 3]])

In [114]:
np.array([4,5,6]).shape


(3,)

In [164]:
out = np.ones(3);
out = out.reshape(out.size, 1)
out = np.c_[out, np.ones(out.shape)]
#out[:, out.shape[1]] = np.ones(6);
out
#out[:, out.shape[1]]

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [165]:
out

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [170]:
out**(4-2) * (out**3)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [176]:
n = 10;
initial_theta = np.zeros((n + 1, 1));
initial_theta = np.c_[initial_theta]
initial_theta
np.sum(np.square(initial_theta))

0.0