In [1]:
import numpy as np
a = np.array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])


In [8]:
a[:, 1]

array([ 2,  5,  8, 11])

In [8]:
y = a[:,1]
y

array([ 2,  5,  8, 11])

In [11]:
m = len(y);
m

4

In [3]:
np.ones(m, int)


NameError: name 'np' is not defined

In [2]:
np.zeros(2, int)


NameError: name 'np' is not defined

In [1]:
a

NameError: name 'a' is not defined

In [21]:
[np.ones(m, int), a[:,1]]

[array([1, 1, 1, 1]), array([ 2,  5,  8, 11])]

In [22]:
print(a)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
b= np.array([1, 2, 3])



In [37]:
b

array([1, 2, 3])

In [26]:
print(np.transpose(b))

[1 2 3]


In [30]:
np.size(a)

12

In [32]:
a.shape


(4, 3)

In [33]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
b

[1, 2, 3]

In [38]:
b.shape

(3,)

In [39]:
c = np.transpose(b)
c.shape

(3,)

In [40]:
c

array([1, 2, 3])

In [43]:
a = np.array([1, 2])
a


array([1, 2])

In [44]:
b = np.array([[5, 6], [7, 8]])
np.matmul(a, b)

array([19, 22])

In [65]:
a = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],[7, 8, 34,4,4,4,5,4,3,2]])
b = np.zeros((2,1))
np.dot(a.T, b)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [60]:
a = np.array([[1, 2], [3, 4]])
a

array([list([1, 2, 3, 4, 5, 6]), list([3, 4])], dtype=object)

array([[1, 2],
       [3, 4]])

In [66]:
np.array([-1, 2])


array([-1,  2])

In [77]:
np.array([-1, 2]).T

array([-1,  2])

In [74]:
np.transpose(np.array([-1, 2]))


array([-1,  2])

In [85]:
np.array([[-1, 2], []]).shape


(2,)

In [76]:
np.array([-1, 2]).T

array([-1,  2])

In [78]:
b = np.zeros((2,1))

In [79]:
b

array([[0.],
       [0.]])

In [2]:
theta = np.zeros((2, 1), int);

In [5]:

theta[1]

array([0])